### ISSUE TITLE
n-gram issues

### ISSUE THREAD

**Issue by tarsius** [uk-ar/key-combo#30]
Does `key-combo` actually use `n-gram`? If so please `require` it otherwise it would probably be best if you moved it to a separate repository. The latter might be a good idea even regardless of whether `key-combo` uses it if `n-gram` is generally useful. Also please add prefixes to the symbols defined in `n-gram`.

**Comment by vspinu** [comment]
`key-combo` is not using `n-gram` file. I have moved it to `old/` subfolder if it's ever needed again.

**Comment by tarsius** [comment]
I think it would be best to remove it in that case, and to rely on the history to bring it back should the need arise. Alternatively you could add the file `old/.nosearch` to prevent `normal-top-level-add-subdirs-to-load-path` (and certain tools I have written) from adding the directory to the `load-path`.
